// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseDomain.proto

package com.fx.productization.datanormalizer.domain.core.dto;

public final class BaseDomainOuterClass {
  private BaseDomainOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseDomainOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.fx.productization.datanormalizer.domain.core.dto.BaseDomain)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 createTime = 1;</code>
     */
    long getCreateTime();

    /**
     * <code>optional int64 lastModifyTime = 2;</code>
     */
    long getLastModifyTime();

    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
     */
    java.util.List<com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute> 
        getAttributesList();
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
     */
    com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute getAttributes(int index);
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
     */
    int getAttributesCount();
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
     */
    java.util.List<? extends com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.AttributeOrBuilder> 
        getAttributesOrBuilderList();
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
     */
    com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.AttributeOrBuilder getAttributesOrBuilder(
        int index);

    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
     */
    java.util.List<com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning> 
        getWarningsList();
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
     */
    com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning getWarnings(int index);
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
     */
    int getWarningsCount();
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
     */
    java.util.List<? extends com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.WarningOrBuilder> 
        getWarningsOrBuilderList();
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
     */
    com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.WarningOrBuilder getWarningsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.fx.productization.datanormalizer.domain.core.dto.BaseDomain}
   */
  public  static final class BaseDomain extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.fx.productization.datanormalizer.domain.core.dto.BaseDomain)
      BaseDomainOrBuilder {
    // Use BaseDomain.newBuilder() to construct.
    private BaseDomain(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseDomain() {
      createTime_ = 0L;
      lastModifyTime_ = 0L;
      attributes_ = java.util.Collections.emptyList();
      warnings_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BaseDomain(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              createTime_ = input.readInt64();
              break;
            }
            case 16: {

              lastModifyTime_ = input.readInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                attributes_ = new java.util.ArrayList<com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute>();
                mutable_bitField0_ |= 0x00000004;
              }
              attributes_.add(
                  input.readMessage(com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute.parser(), extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                warnings_ = new java.util.ArrayList<com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning>();
                mutable_bitField0_ |= 0x00000008;
              }
              warnings_.add(
                  input.readMessage(com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          attributes_ = java.util.Collections.unmodifiableList(attributes_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          warnings_ = java.util.Collections.unmodifiableList(warnings_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_BaseDomain_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_BaseDomain_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.class, com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.Builder.class);
    }

    private int bitField0_;
    public static final int CREATETIME_FIELD_NUMBER = 1;
    private long createTime_;
    /**
     * <code>optional int64 createTime = 1;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    public static final int LASTMODIFYTIME_FIELD_NUMBER = 2;
    private long lastModifyTime_;
    /**
     * <code>optional int64 lastModifyTime = 2;</code>
     */
    public long getLastModifyTime() {
      return lastModifyTime_;
    }

    public static final int ATTRIBUTES_FIELD_NUMBER = 3;
    private java.util.List<com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute> attributes_;
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
     */
    public java.util.List<com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute> getAttributesList() {
      return attributes_;
    }
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
     */
    public java.util.List<? extends com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.AttributeOrBuilder> 
        getAttributesOrBuilderList() {
      return attributes_;
    }
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
     */
    public int getAttributesCount() {
      return attributes_.size();
    }
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
     */
    public com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute getAttributes(int index) {
      return attributes_.get(index);
    }
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
     */
    public com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.AttributeOrBuilder getAttributesOrBuilder(
        int index) {
      return attributes_.get(index);
    }

    public static final int WARNINGS_FIELD_NUMBER = 4;
    private java.util.List<com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning> warnings_;
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
     */
    public java.util.List<com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning> getWarningsList() {
      return warnings_;
    }
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
     */
    public java.util.List<? extends com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.WarningOrBuilder> 
        getWarningsOrBuilderList() {
      return warnings_;
    }
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
     */
    public int getWarningsCount() {
      return warnings_.size();
    }
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
     */
    public com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning getWarnings(int index) {
      return warnings_.get(index);
    }
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
     */
    public com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.WarningOrBuilder getWarningsOrBuilder(
        int index) {
      return warnings_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (createTime_ != 0L) {
        output.writeInt64(1, createTime_);
      }
      if (lastModifyTime_ != 0L) {
        output.writeInt64(2, lastModifyTime_);
      }
      for (int i = 0; i < attributes_.size(); i++) {
        output.writeMessage(3, attributes_.get(i));
      }
      for (int i = 0; i < warnings_.size(); i++) {
        output.writeMessage(4, warnings_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, createTime_);
      }
      if (lastModifyTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, lastModifyTime_);
      }
      for (int i = 0; i < attributes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, attributes_.get(i));
      }
      for (int i = 0; i < warnings_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, warnings_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain)) {
        return super.equals(obj);
      }
      com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain other = (com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain) obj;

      boolean result = true;
      result = result && (getCreateTime()
          == other.getCreateTime());
      result = result && (getLastModifyTime()
          == other.getLastModifyTime());
      result = result && getAttributesList()
          .equals(other.getAttributesList());
      result = result && getWarningsList()
          .equals(other.getWarningsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (37 * hash) + LASTMODIFYTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastModifyTime());
      if (getAttributesCount() > 0) {
        hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
        hash = (53 * hash) + getAttributesList().hashCode();
      }
      if (getWarningsCount() > 0) {
        hash = (37 * hash) + WARNINGS_FIELD_NUMBER;
        hash = (53 * hash) + getWarningsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.fx.productization.datanormalizer.domain.core.dto.BaseDomain}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.fx.productization.datanormalizer.domain.core.dto.BaseDomain)
        com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomainOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_BaseDomain_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_BaseDomain_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.class, com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.Builder.class);
      }

      // Construct using com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAttributesFieldBuilder();
          getWarningsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        createTime_ = 0L;

        lastModifyTime_ = 0L;

        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          attributesBuilder_.clear();
        }
        if (warningsBuilder_ == null) {
          warnings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          warningsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_BaseDomain_descriptor;
      }

      public com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain getDefaultInstanceForType() {
        return com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.getDefaultInstance();
      }

      public com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain build() {
        com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain buildPartial() {
        com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain result = new com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.createTime_ = createTime_;
        result.lastModifyTime_ = lastModifyTime_;
        if (attributesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            attributes_ = java.util.Collections.unmodifiableList(attributes_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.attributes_ = attributes_;
        } else {
          result.attributes_ = attributesBuilder_.build();
        }
        if (warningsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            warnings_ = java.util.Collections.unmodifiableList(warnings_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.warnings_ = warnings_;
        } else {
          result.warnings_ = warningsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain) {
          return mergeFrom((com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain other) {
        if (other == com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.getDefaultInstance()) return this;
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (other.getLastModifyTime() != 0L) {
          setLastModifyTime(other.getLastModifyTime());
        }
        if (attributesBuilder_ == null) {
          if (!other.attributes_.isEmpty()) {
            if (attributes_.isEmpty()) {
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAttributesIsMutable();
              attributes_.addAll(other.attributes_);
            }
            onChanged();
          }
        } else {
          if (!other.attributes_.isEmpty()) {
            if (attributesBuilder_.isEmpty()) {
              attributesBuilder_.dispose();
              attributesBuilder_ = null;
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000004);
              attributesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAttributesFieldBuilder() : null;
            } else {
              attributesBuilder_.addAllMessages(other.attributes_);
            }
          }
        }
        if (warningsBuilder_ == null) {
          if (!other.warnings_.isEmpty()) {
            if (warnings_.isEmpty()) {
              warnings_ = other.warnings_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureWarningsIsMutable();
              warnings_.addAll(other.warnings_);
            }
            onChanged();
          }
        } else {
          if (!other.warnings_.isEmpty()) {
            if (warningsBuilder_.isEmpty()) {
              warningsBuilder_.dispose();
              warningsBuilder_ = null;
              warnings_ = other.warnings_;
              bitField0_ = (bitField0_ & ~0x00000008);
              warningsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getWarningsFieldBuilder() : null;
            } else {
              warningsBuilder_.addAllMessages(other.warnings_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long createTime_ ;
      /**
       * <code>optional int64 createTime = 1;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>optional int64 createTime = 1;</code>
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 createTime = 1;</code>
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private long lastModifyTime_ ;
      /**
       * <code>optional int64 lastModifyTime = 2;</code>
       */
      public long getLastModifyTime() {
        return lastModifyTime_;
      }
      /**
       * <code>optional int64 lastModifyTime = 2;</code>
       */
      public Builder setLastModifyTime(long value) {
        
        lastModifyTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 lastModifyTime = 2;</code>
       */
      public Builder clearLastModifyTime() {
        
        lastModifyTime_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute> attributes_ =
        java.util.Collections.emptyList();
      private void ensureAttributesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          attributes_ = new java.util.ArrayList<com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute>(attributes_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute, com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute.Builder, com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.AttributeOrBuilder> attributesBuilder_;

      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
       */
      public java.util.List<com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute> getAttributesList() {
        if (attributesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attributes_);
        } else {
          return attributesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
       */
      public int getAttributesCount() {
        if (attributesBuilder_ == null) {
          return attributes_.size();
        } else {
          return attributesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute getAttributes(int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);
        } else {
          return attributesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
       */
      public Builder setAttributes(
          int index, com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.set(index, value);
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
       */
      public Builder setAttributes(
          int index, com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.set(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
       */
      public Builder addAttributes(com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
       */
      public Builder addAttributes(
          int index, com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(index, value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
       */
      public Builder addAttributes(
          com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
       */
      public Builder addAttributes(
          int index, com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
       */
      public Builder addAllAttributes(
          java.lang.Iterable<? extends com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute> values) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, attributes_);
          onChanged();
        } else {
          attributesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
       */
      public Builder clearAttributes() {
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          attributesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
       */
      public Builder removeAttributes(int index) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.remove(index);
          onChanged();
        } else {
          attributesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute.Builder getAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.AttributeOrBuilder getAttributesOrBuilder(
          int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);  } else {
          return attributesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
       */
      public java.util.List<? extends com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.AttributeOrBuilder> 
           getAttributesOrBuilderList() {
        if (attributesBuilder_ != null) {
          return attributesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attributes_);
        }
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute.Builder addAttributesBuilder() {
        return getAttributesFieldBuilder().addBuilder(
            com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute.getDefaultInstance());
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute.Builder addAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().addBuilder(
            index, com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute.getDefaultInstance());
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Attribute attributes = 3;</code>
       */
      public java.util.List<com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute.Builder> 
           getAttributesBuilderList() {
        return getAttributesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute, com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute.Builder, com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.AttributeOrBuilder> 
          getAttributesFieldBuilder() {
        if (attributesBuilder_ == null) {
          attributesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute, com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.Attribute.Builder, com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.AttributeOrBuilder>(
                  attributes_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          attributes_ = null;
        }
        return attributesBuilder_;
      }

      private java.util.List<com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning> warnings_ =
        java.util.Collections.emptyList();
      private void ensureWarningsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          warnings_ = new java.util.ArrayList<com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning>(warnings_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning, com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning.Builder, com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.WarningOrBuilder> warningsBuilder_;

      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
       */
      public java.util.List<com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning> getWarningsList() {
        if (warningsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(warnings_);
        } else {
          return warningsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
       */
      public int getWarningsCount() {
        if (warningsBuilder_ == null) {
          return warnings_.size();
        } else {
          return warningsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning getWarnings(int index) {
        if (warningsBuilder_ == null) {
          return warnings_.get(index);
        } else {
          return warningsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
       */
      public Builder setWarnings(
          int index, com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning value) {
        if (warningsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWarningsIsMutable();
          warnings_.set(index, value);
          onChanged();
        } else {
          warningsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
       */
      public Builder setWarnings(
          int index, com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning.Builder builderForValue) {
        if (warningsBuilder_ == null) {
          ensureWarningsIsMutable();
          warnings_.set(index, builderForValue.build());
          onChanged();
        } else {
          warningsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
       */
      public Builder addWarnings(com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning value) {
        if (warningsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWarningsIsMutable();
          warnings_.add(value);
          onChanged();
        } else {
          warningsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
       */
      public Builder addWarnings(
          int index, com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning value) {
        if (warningsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWarningsIsMutable();
          warnings_.add(index, value);
          onChanged();
        } else {
          warningsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
       */
      public Builder addWarnings(
          com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning.Builder builderForValue) {
        if (warningsBuilder_ == null) {
          ensureWarningsIsMutable();
          warnings_.add(builderForValue.build());
          onChanged();
        } else {
          warningsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
       */
      public Builder addWarnings(
          int index, com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning.Builder builderForValue) {
        if (warningsBuilder_ == null) {
          ensureWarningsIsMutable();
          warnings_.add(index, builderForValue.build());
          onChanged();
        } else {
          warningsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
       */
      public Builder addAllWarnings(
          java.lang.Iterable<? extends com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning> values) {
        if (warningsBuilder_ == null) {
          ensureWarningsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, warnings_);
          onChanged();
        } else {
          warningsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
       */
      public Builder clearWarnings() {
        if (warningsBuilder_ == null) {
          warnings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          warningsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
       */
      public Builder removeWarnings(int index) {
        if (warningsBuilder_ == null) {
          ensureWarningsIsMutable();
          warnings_.remove(index);
          onChanged();
        } else {
          warningsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning.Builder getWarningsBuilder(
          int index) {
        return getWarningsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.WarningOrBuilder getWarningsOrBuilder(
          int index) {
        if (warningsBuilder_ == null) {
          return warnings_.get(index);  } else {
          return warningsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
       */
      public java.util.List<? extends com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.WarningOrBuilder> 
           getWarningsOrBuilderList() {
        if (warningsBuilder_ != null) {
          return warningsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(warnings_);
        }
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning.Builder addWarningsBuilder() {
        return getWarningsFieldBuilder().addBuilder(
            com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning.getDefaultInstance());
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning.Builder addWarningsBuilder(
          int index) {
        return getWarningsFieldBuilder().addBuilder(
            index, com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning.getDefaultInstance());
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.Warning warnings = 4;</code>
       */
      public java.util.List<com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning.Builder> 
           getWarningsBuilderList() {
        return getWarningsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning, com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning.Builder, com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.WarningOrBuilder> 
          getWarningsFieldBuilder() {
        if (warningsBuilder_ == null) {
          warningsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning, com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.Warning.Builder, com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.WarningOrBuilder>(
                  warnings_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          warnings_ = null;
        }
        return warningsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.fx.productization.datanormalizer.domain.core.dto.BaseDomain)
    }

    // @@protoc_insertion_point(class_scope:com.fx.productization.datanormalizer.domain.core.dto.BaseDomain)
    private static final com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain();
    }

    public static com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseDomain>
        PARSER = new com.google.protobuf.AbstractParser<BaseDomain>() {
      public BaseDomain parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BaseDomain(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseDomain> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseDomain> getParserForType() {
      return PARSER;
    }

    public com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fx_productization_datanormalizer_domain_core_dto_BaseDomain_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fx_productization_datanormalizer_domain_core_dto_BaseDomain_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020BaseDomain.proto\0224com.fx.productizatio" +
      "n.datanormalizer.domain.core.dto\032\017Attrib" +
      "ute.proto\032\rWarning.proto\"\336\001\n\nBaseDomain\022" +
      "\022\n\ncreateTime\030\001 \001(\003\022\026\n\016lastModifyTime\030\002 " +
      "\001(\003\022S\n\nattributes\030\003 \003(\0132?.com.fx.product" +
      "ization.datanormalizer.domain.core.dto.A" +
      "ttribute\022O\n\010warnings\030\004 \003(\0132=.com.fx.prod" +
      "uctization.datanormalizer.domain.core.dt" +
      "o.Warningb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.getDescriptor(),
          com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_fx_productization_datanormalizer_domain_core_dto_BaseDomain_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fx_productization_datanormalizer_domain_core_dto_BaseDomain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fx_productization_datanormalizer_domain_core_dto_BaseDomain_descriptor,
        new java.lang.String[] { "CreateTime", "LastModifyTime", "Attributes", "Warnings", });
    com.fx.productization.datanormalizer.domain.core.dto.AttributeOuterClass.getDescriptor();
    com.fx.productization.datanormalizer.domain.core.dto.WarningOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
