// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Behaviour.proto

package com.fx.productization.datanormalizer.domain.core.dto;

public final class BehaviourOuterClass {
  private BehaviourOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BehaviourOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.fx.productization.datanormalizer.domain.core.dto.Behaviour)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
     */
    boolean hasBaseDomain();
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
     */
    com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain getBaseDomain();
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
     */
    com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomainOrBuilder getBaseDomainOrBuilder();

    /**
     * <code>optional int64 id = 2;</code>
     */
    long getId();

    /**
     * <code>optional int64 sourceBehaviourId = 3;</code>
     */
    long getSourceBehaviourId();

    /**
     * <code>optional int64 companyId = 4;</code>
     */
    long getCompanyId();

    /**
     * <code>optional int64 platformId = 5;</code>
     */
    long getPlatformId();

    /**
     * <code>optional int64 customerId = 6;</code>
     */
    long getCustomerId();

    /**
     * <code>optional int64 channelId = 7;</code>
     */
    long getChannelId();

    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BehaviourType type = 8;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BehaviourType type = 8;</code>
     */
    com.fx.productization.datanormalizer.domain.core.dto.BehaviourTypeOuterClass.BehaviourType getType();

    /**
     * <code>optional int64 time = 9;</code>
     */
    long getTime();
  }
  /**
   * Protobuf type {@code com.fx.productization.datanormalizer.domain.core.dto.Behaviour}
   */
  public  static final class Behaviour extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.fx.productization.datanormalizer.domain.core.dto.Behaviour)
      BehaviourOrBuilder {
    // Use Behaviour.newBuilder() to construct.
    private Behaviour(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Behaviour() {
      id_ = 0L;
      sourceBehaviourId_ = 0L;
      companyId_ = 0L;
      platformId_ = 0L;
      customerId_ = 0L;
      channelId_ = 0L;
      type_ = 0;
      time_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Behaviour(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.Builder subBuilder = null;
              if (baseDomain_ != null) {
                subBuilder = baseDomain_.toBuilder();
              }
              baseDomain_ = input.readMessage(com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseDomain_);
                baseDomain_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              id_ = input.readInt64();
              break;
            }
            case 24: {

              sourceBehaviourId_ = input.readInt64();
              break;
            }
            case 32: {

              companyId_ = input.readInt64();
              break;
            }
            case 40: {

              platformId_ = input.readInt64();
              break;
            }
            case 48: {

              customerId_ = input.readInt64();
              break;
            }
            case 56: {

              channelId_ = input.readInt64();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 72: {

              time_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_Behaviour_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_Behaviour_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour.class, com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour.Builder.class);
    }

    public static final int BASEDOMAIN_FIELD_NUMBER = 1;
    private com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain baseDomain_;
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
     */
    public boolean hasBaseDomain() {
      return baseDomain_ != null;
    }
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
     */
    public com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain getBaseDomain() {
      return baseDomain_ == null ? com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.getDefaultInstance() : baseDomain_;
    }
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
     */
    public com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomainOrBuilder getBaseDomainOrBuilder() {
      return getBaseDomain();
    }

    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <code>optional int64 id = 2;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int SOURCEBEHAVIOURID_FIELD_NUMBER = 3;
    private long sourceBehaviourId_;
    /**
     * <code>optional int64 sourceBehaviourId = 3;</code>
     */
    public long getSourceBehaviourId() {
      return sourceBehaviourId_;
    }

    public static final int COMPANYID_FIELD_NUMBER = 4;
    private long companyId_;
    /**
     * <code>optional int64 companyId = 4;</code>
     */
    public long getCompanyId() {
      return companyId_;
    }

    public static final int PLATFORMID_FIELD_NUMBER = 5;
    private long platformId_;
    /**
     * <code>optional int64 platformId = 5;</code>
     */
    public long getPlatformId() {
      return platformId_;
    }

    public static final int CUSTOMERID_FIELD_NUMBER = 6;
    private long customerId_;
    /**
     * <code>optional int64 customerId = 6;</code>
     */
    public long getCustomerId() {
      return customerId_;
    }

    public static final int CHANNELID_FIELD_NUMBER = 7;
    private long channelId_;
    /**
     * <code>optional int64 channelId = 7;</code>
     */
    public long getChannelId() {
      return channelId_;
    }

    public static final int TYPE_FIELD_NUMBER = 8;
    private int type_;
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BehaviourType type = 8;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BehaviourType type = 8;</code>
     */
    public com.fx.productization.datanormalizer.domain.core.dto.BehaviourTypeOuterClass.BehaviourType getType() {
      com.fx.productization.datanormalizer.domain.core.dto.BehaviourTypeOuterClass.BehaviourType result = com.fx.productization.datanormalizer.domain.core.dto.BehaviourTypeOuterClass.BehaviourType.valueOf(type_);
      return result == null ? com.fx.productization.datanormalizer.domain.core.dto.BehaviourTypeOuterClass.BehaviourType.UNRECOGNIZED : result;
    }

    public static final int TIME_FIELD_NUMBER = 9;
    private long time_;
    /**
     * <code>optional int64 time = 9;</code>
     */
    public long getTime() {
      return time_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (baseDomain_ != null) {
        output.writeMessage(1, getBaseDomain());
      }
      if (id_ != 0L) {
        output.writeInt64(2, id_);
      }
      if (sourceBehaviourId_ != 0L) {
        output.writeInt64(3, sourceBehaviourId_);
      }
      if (companyId_ != 0L) {
        output.writeInt64(4, companyId_);
      }
      if (platformId_ != 0L) {
        output.writeInt64(5, platformId_);
      }
      if (customerId_ != 0L) {
        output.writeInt64(6, customerId_);
      }
      if (channelId_ != 0L) {
        output.writeInt64(7, channelId_);
      }
      if (type_ != com.fx.productization.datanormalizer.domain.core.dto.BehaviourTypeOuterClass.BehaviourType.Browse.getNumber()) {
        output.writeEnum(8, type_);
      }
      if (time_ != 0L) {
        output.writeInt64(9, time_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (baseDomain_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBaseDomain());
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, id_);
      }
      if (sourceBehaviourId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sourceBehaviourId_);
      }
      if (companyId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, companyId_);
      }
      if (platformId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, platformId_);
      }
      if (customerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, customerId_);
      }
      if (channelId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, channelId_);
      }
      if (type_ != com.fx.productization.datanormalizer.domain.core.dto.BehaviourTypeOuterClass.BehaviourType.Browse.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, type_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, time_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour)) {
        return super.equals(obj);
      }
      com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour other = (com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour) obj;

      boolean result = true;
      result = result && (hasBaseDomain() == other.hasBaseDomain());
      if (hasBaseDomain()) {
        result = result && getBaseDomain()
            .equals(other.getBaseDomain());
      }
      result = result && (getId()
          == other.getId());
      result = result && (getSourceBehaviourId()
          == other.getSourceBehaviourId());
      result = result && (getCompanyId()
          == other.getCompanyId());
      result = result && (getPlatformId()
          == other.getPlatformId());
      result = result && (getCustomerId()
          == other.getCustomerId());
      result = result && (getChannelId()
          == other.getChannelId());
      result = result && type_ == other.type_;
      result = result && (getTime()
          == other.getTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasBaseDomain()) {
        hash = (37 * hash) + BASEDOMAIN_FIELD_NUMBER;
        hash = (53 * hash) + getBaseDomain().hashCode();
      }
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + SOURCEBEHAVIOURID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSourceBehaviourId());
      hash = (37 * hash) + COMPANYID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCompanyId());
      hash = (37 * hash) + PLATFORMID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlatformId());
      hash = (37 * hash) + CUSTOMERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCustomerId());
      hash = (37 * hash) + CHANNELID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getChannelId());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.fx.productization.datanormalizer.domain.core.dto.Behaviour}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.fx.productization.datanormalizer.domain.core.dto.Behaviour)
        com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.BehaviourOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_Behaviour_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_Behaviour_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour.class, com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour.Builder.class);
      }

      // Construct using com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (baseDomainBuilder_ == null) {
          baseDomain_ = null;
        } else {
          baseDomain_ = null;
          baseDomainBuilder_ = null;
        }
        id_ = 0L;

        sourceBehaviourId_ = 0L;

        companyId_ = 0L;

        platformId_ = 0L;

        customerId_ = 0L;

        channelId_ = 0L;

        type_ = 0;

        time_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_Behaviour_descriptor;
      }

      public com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour getDefaultInstanceForType() {
        return com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour.getDefaultInstance();
      }

      public com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour build() {
        com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour buildPartial() {
        com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour result = new com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour(this);
        if (baseDomainBuilder_ == null) {
          result.baseDomain_ = baseDomain_;
        } else {
          result.baseDomain_ = baseDomainBuilder_.build();
        }
        result.id_ = id_;
        result.sourceBehaviourId_ = sourceBehaviourId_;
        result.companyId_ = companyId_;
        result.platformId_ = platformId_;
        result.customerId_ = customerId_;
        result.channelId_ = channelId_;
        result.type_ = type_;
        result.time_ = time_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour) {
          return mergeFrom((com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour other) {
        if (other == com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour.getDefaultInstance()) return this;
        if (other.hasBaseDomain()) {
          mergeBaseDomain(other.getBaseDomain());
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getSourceBehaviourId() != 0L) {
          setSourceBehaviourId(other.getSourceBehaviourId());
        }
        if (other.getCompanyId() != 0L) {
          setCompanyId(other.getCompanyId());
        }
        if (other.getPlatformId() != 0L) {
          setPlatformId(other.getPlatformId());
        }
        if (other.getCustomerId() != 0L) {
          setCustomerId(other.getCustomerId());
        }
        if (other.getChannelId() != 0L) {
          setChannelId(other.getChannelId());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain baseDomain_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain, com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.Builder, com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomainOrBuilder> baseDomainBuilder_;
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
       */
      public boolean hasBaseDomain() {
        return baseDomainBuilder_ != null || baseDomain_ != null;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain getBaseDomain() {
        if (baseDomainBuilder_ == null) {
          return baseDomain_ == null ? com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.getDefaultInstance() : baseDomain_;
        } else {
          return baseDomainBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
       */
      public Builder setBaseDomain(com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain value) {
        if (baseDomainBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseDomain_ = value;
          onChanged();
        } else {
          baseDomainBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
       */
      public Builder setBaseDomain(
          com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.Builder builderForValue) {
        if (baseDomainBuilder_ == null) {
          baseDomain_ = builderForValue.build();
          onChanged();
        } else {
          baseDomainBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
       */
      public Builder mergeBaseDomain(com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain value) {
        if (baseDomainBuilder_ == null) {
          if (baseDomain_ != null) {
            baseDomain_ =
              com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.newBuilder(baseDomain_).mergeFrom(value).buildPartial();
          } else {
            baseDomain_ = value;
          }
          onChanged();
        } else {
          baseDomainBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
       */
      public Builder clearBaseDomain() {
        if (baseDomainBuilder_ == null) {
          baseDomain_ = null;
          onChanged();
        } else {
          baseDomain_ = null;
          baseDomainBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.Builder getBaseDomainBuilder() {
        
        onChanged();
        return getBaseDomainFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomainOrBuilder getBaseDomainOrBuilder() {
        if (baseDomainBuilder_ != null) {
          return baseDomainBuilder_.getMessageOrBuilder();
        } else {
          return baseDomain_ == null ?
              com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.getDefaultInstance() : baseDomain_;
        }
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain, com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.Builder, com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomainOrBuilder> 
          getBaseDomainFieldBuilder() {
        if (baseDomainBuilder_ == null) {
          baseDomainBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain, com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.Builder, com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomainOrBuilder>(
                  getBaseDomain(),
                  getParentForChildren(),
                  isClean());
          baseDomain_ = null;
        }
        return baseDomainBuilder_;
      }

      private long id_ ;
      /**
       * <code>optional int64 id = 2;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 2;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 2;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long sourceBehaviourId_ ;
      /**
       * <code>optional int64 sourceBehaviourId = 3;</code>
       */
      public long getSourceBehaviourId() {
        return sourceBehaviourId_;
      }
      /**
       * <code>optional int64 sourceBehaviourId = 3;</code>
       */
      public Builder setSourceBehaviourId(long value) {
        
        sourceBehaviourId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sourceBehaviourId = 3;</code>
       */
      public Builder clearSourceBehaviourId() {
        
        sourceBehaviourId_ = 0L;
        onChanged();
        return this;
      }

      private long companyId_ ;
      /**
       * <code>optional int64 companyId = 4;</code>
       */
      public long getCompanyId() {
        return companyId_;
      }
      /**
       * <code>optional int64 companyId = 4;</code>
       */
      public Builder setCompanyId(long value) {
        
        companyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 companyId = 4;</code>
       */
      public Builder clearCompanyId() {
        
        companyId_ = 0L;
        onChanged();
        return this;
      }

      private long platformId_ ;
      /**
       * <code>optional int64 platformId = 5;</code>
       */
      public long getPlatformId() {
        return platformId_;
      }
      /**
       * <code>optional int64 platformId = 5;</code>
       */
      public Builder setPlatformId(long value) {
        
        platformId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 platformId = 5;</code>
       */
      public Builder clearPlatformId() {
        
        platformId_ = 0L;
        onChanged();
        return this;
      }

      private long customerId_ ;
      /**
       * <code>optional int64 customerId = 6;</code>
       */
      public long getCustomerId() {
        return customerId_;
      }
      /**
       * <code>optional int64 customerId = 6;</code>
       */
      public Builder setCustomerId(long value) {
        
        customerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 customerId = 6;</code>
       */
      public Builder clearCustomerId() {
        
        customerId_ = 0L;
        onChanged();
        return this;
      }

      private long channelId_ ;
      /**
       * <code>optional int64 channelId = 7;</code>
       */
      public long getChannelId() {
        return channelId_;
      }
      /**
       * <code>optional int64 channelId = 7;</code>
       */
      public Builder setChannelId(long value) {
        
        channelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 channelId = 7;</code>
       */
      public Builder clearChannelId() {
        
        channelId_ = 0L;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BehaviourType type = 8;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BehaviourType type = 8;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BehaviourType type = 8;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.BehaviourTypeOuterClass.BehaviourType getType() {
        com.fx.productization.datanormalizer.domain.core.dto.BehaviourTypeOuterClass.BehaviourType result = com.fx.productization.datanormalizer.domain.core.dto.BehaviourTypeOuterClass.BehaviourType.valueOf(type_);
        return result == null ? com.fx.productization.datanormalizer.domain.core.dto.BehaviourTypeOuterClass.BehaviourType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BehaviourType type = 8;</code>
       */
      public Builder setType(com.fx.productization.datanormalizer.domain.core.dto.BehaviourTypeOuterClass.BehaviourType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BehaviourType type = 8;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>optional int64 time = 9;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional int64 time = 9;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 time = 9;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.fx.productization.datanormalizer.domain.core.dto.Behaviour)
    }

    // @@protoc_insertion_point(class_scope:com.fx.productization.datanormalizer.domain.core.dto.Behaviour)
    private static final com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour();
    }

    public static com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Behaviour>
        PARSER = new com.google.protobuf.AbstractParser<Behaviour>() {
      public Behaviour parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Behaviour(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Behaviour> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Behaviour> getParserForType() {
      return PARSER;
    }

    public com.fx.productization.datanormalizer.domain.core.dto.BehaviourOuterClass.Behaviour getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fx_productization_datanormalizer_domain_core_dto_Behaviour_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fx_productization_datanormalizer_domain_core_dto_Behaviour_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Behaviour.proto\0224com.fx.productization" +
      ".datanormalizer.domain.core.dto\032\020BaseDom" +
      "ain.proto\032\023BehaviourType.proto\"\267\002\n\tBehav" +
      "iour\022T\n\nbaseDomain\030\001 \001(\0132@.com.fx.produc" +
      "tization.datanormalizer.domain.core.dto." +
      "BaseDomain\022\n\n\002id\030\002 \001(\003\022\031\n\021sourceBehaviou" +
      "rId\030\003 \001(\003\022\021\n\tcompanyId\030\004 \001(\003\022\022\n\nplatform" +
      "Id\030\005 \001(\003\022\022\n\ncustomerId\030\006 \001(\003\022\021\n\tchannelI" +
      "d\030\007 \001(\003\022Q\n\004type\030\010 \001(\0162C.com.fx.productiz" +
      "ation.datanormalizer.domain.core.dto.Beh",
      "aviourType\022\014\n\004time\030\t \001(\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.getDescriptor(),
          com.fx.productization.datanormalizer.domain.core.dto.BehaviourTypeOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_fx_productization_datanormalizer_domain_core_dto_Behaviour_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fx_productization_datanormalizer_domain_core_dto_Behaviour_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fx_productization_datanormalizer_domain_core_dto_Behaviour_descriptor,
        new java.lang.String[] { "BaseDomain", "Id", "SourceBehaviourId", "CompanyId", "PlatformId", "CustomerId", "ChannelId", "Type", "Time", });
    com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.getDescriptor();
    com.fx.productization.datanormalizer.domain.core.dto.BehaviourTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
