// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package com.fx.productization.datanormalizer.domain.core.dto;

public final class CustomerOuterClass {
  private CustomerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CustomerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.fx.productization.datanormalizer.domain.core.dto.Customer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
     */
    boolean hasBaseDomain();
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
     */
    com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain getBaseDomain();
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
     */
    com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomainOrBuilder getBaseDomainOrBuilder();

    /**
     * <code>optional int64 id = 2;</code>
     */
    long getId();

    /**
     * <code>optional int64 companyId = 3;</code>
     */
    long getCompanyId();

    /**
     * <code>optional int64 platformId = 4;</code>
     */
    long getPlatformId();

    /**
     * <code>optional string name = 5;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 5;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string identityNos = 6;</code>
     */
    java.lang.String getIdentityNos();
    /**
     * <code>optional string identityNos = 6;</code>
     */
    com.google.protobuf.ByteString
        getIdentityNosBytes();

    /**
     * <code>optional string gender = 7;</code>
     */
    java.lang.String getGender();
    /**
     * <code>optional string gender = 7;</code>
     */
    com.google.protobuf.ByteString
        getGenderBytes();

    /**
     * <code>repeated string mobiles = 8;</code>
     */
    java.util.List<java.lang.String>
        getMobilesList();
    /**
     * <code>repeated string mobiles = 8;</code>
     */
    int getMobilesCount();
    /**
     * <code>repeated string mobiles = 8;</code>
     */
    java.lang.String getMobiles(int index);
    /**
     * <code>repeated string mobiles = 8;</code>
     */
    com.google.protobuf.ByteString
        getMobilesBytes(int index);

    /**
     * <code>repeated string phones = 9;</code>
     */
    java.util.List<java.lang.String>
        getPhonesList();
    /**
     * <code>repeated string phones = 9;</code>
     */
    int getPhonesCount();
    /**
     * <code>repeated string phones = 9;</code>
     */
    java.lang.String getPhones(int index);
    /**
     * <code>repeated string phones = 9;</code>
     */
    com.google.protobuf.ByteString
        getPhonesBytes(int index);

    /**
     * <code>repeated string emails = 10;</code>
     */
    java.util.List<java.lang.String>
        getEmailsList();
    /**
     * <code>repeated string emails = 10;</code>
     */
    int getEmailsCount();
    /**
     * <code>repeated string emails = 10;</code>
     */
    java.lang.String getEmails(int index);
    /**
     * <code>repeated string emails = 10;</code>
     */
    com.google.protobuf.ByteString
        getEmailsBytes(int index);

    /**
     * <code>repeated int64 birthdays = 11;</code>
     */
    java.util.List<java.lang.Long> getBirthdaysList();
    /**
     * <code>repeated int64 birthdays = 11;</code>
     */
    int getBirthdaysCount();
    /**
     * <code>repeated int64 birthdays = 11;</code>
     */
    long getBirthdays(int index);

    /**
     * <code>repeated string addresses = 12;</code>
     */
    java.util.List<java.lang.String>
        getAddressesList();
    /**
     * <code>repeated string addresses = 12;</code>
     */
    int getAddressesCount();
    /**
     * <code>repeated string addresses = 12;</code>
     */
    java.lang.String getAddresses(int index);
    /**
     * <code>repeated string addresses = 12;</code>
     */
    com.google.protobuf.ByteString
        getAddressesBytes(int index);

    /**
     * <code>optional string account = 13;</code>
     */
    java.lang.String getAccount();
    /**
     * <code>optional string account = 13;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
     */
    java.util.List<com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount> 
        getPayAccountsList();
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
     */
    com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount getPayAccounts(int index);
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
     */
    int getPayAccountsCount();
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
     */
    java.util.List<? extends com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccountOrBuilder> 
        getPayAccountsOrBuilderList();
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
     */
    com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccountOrBuilder getPayAccountsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.fx.productization.datanormalizer.domain.core.dto.Customer}
   */
  public  static final class Customer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.fx.productization.datanormalizer.domain.core.dto.Customer)
      CustomerOrBuilder {
    // Use Customer.newBuilder() to construct.
    private Customer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Customer() {
      id_ = 0L;
      companyId_ = 0L;
      platformId_ = 0L;
      name_ = "";
      identityNos_ = "";
      gender_ = "";
      mobiles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      emails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      birthdays_ = java.util.Collections.emptyList();
      addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      account_ = "";
      payAccounts_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Customer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.Builder subBuilder = null;
              if (baseDomain_ != null) {
                subBuilder = baseDomain_.toBuilder();
              }
              baseDomain_ = input.readMessage(com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseDomain_);
                baseDomain_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              id_ = input.readInt64();
              break;
            }
            case 24: {

              companyId_ = input.readInt64();
              break;
            }
            case 32: {

              platformId_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              identityNos_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              gender_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                mobiles_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000080;
              }
              mobiles_.add(s);
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                phones_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000100;
              }
              phones_.add(s);
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
                emails_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000200;
              }
              emails_.add(s);
              break;
            }
            case 88: {
              if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
                birthdays_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000400;
              }
              birthdays_.add(input.readInt64());
              break;
            }
            case 90: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000400) == 0x00000400) && input.getBytesUntilLimit() > 0) {
                birthdays_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000400;
              }
              while (input.getBytesUntilLimit() > 0) {
                birthdays_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000800) == 0x00000800)) {
                addresses_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000800;
              }
              addresses_.add(s);
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              account_ = s;
              break;
            }
            case 114: {
              if (!((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
                payAccounts_ = new java.util.ArrayList<com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount>();
                mutable_bitField0_ |= 0x00002000;
              }
              payAccounts_.add(
                  input.readMessage(com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          mobiles_ = mobiles_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          phones_ = phones_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
          emails_ = emails_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
          birthdays_ = java.util.Collections.unmodifiableList(birthdays_);
        }
        if (((mutable_bitField0_ & 0x00000800) == 0x00000800)) {
          addresses_ = addresses_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
          payAccounts_ = java.util.Collections.unmodifiableList(payAccounts_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_Customer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_Customer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer.class, com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer.Builder.class);
    }

    private int bitField0_;
    public static final int BASEDOMAIN_FIELD_NUMBER = 1;
    private com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain baseDomain_;
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
     */
    public boolean hasBaseDomain() {
      return baseDomain_ != null;
    }
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
     */
    public com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain getBaseDomain() {
      return baseDomain_ == null ? com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.getDefaultInstance() : baseDomain_;
    }
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
     */
    public com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomainOrBuilder getBaseDomainOrBuilder() {
      return getBaseDomain();
    }

    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <code>optional int64 id = 2;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int COMPANYID_FIELD_NUMBER = 3;
    private long companyId_;
    /**
     * <code>optional int64 companyId = 3;</code>
     */
    public long getCompanyId() {
      return companyId_;
    }

    public static final int PLATFORMID_FIELD_NUMBER = 4;
    private long platformId_;
    /**
     * <code>optional int64 platformId = 4;</code>
     */
    public long getPlatformId() {
      return platformId_;
    }

    public static final int NAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 5;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDENTITYNOS_FIELD_NUMBER = 6;
    private volatile java.lang.Object identityNos_;
    /**
     * <code>optional string identityNos = 6;</code>
     */
    public java.lang.String getIdentityNos() {
      java.lang.Object ref = identityNos_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        identityNos_ = s;
        return s;
      }
    }
    /**
     * <code>optional string identityNos = 6;</code>
     */
    public com.google.protobuf.ByteString
        getIdentityNosBytes() {
      java.lang.Object ref = identityNos_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identityNos_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 7;
    private volatile java.lang.Object gender_;
    /**
     * <code>optional string gender = 7;</code>
     */
    public java.lang.String getGender() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gender_ = s;
        return s;
      }
    }
    /**
     * <code>optional string gender = 7;</code>
     */
    public com.google.protobuf.ByteString
        getGenderBytes() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOBILES_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList mobiles_;
    /**
     * <code>repeated string mobiles = 8;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMobilesList() {
      return mobiles_;
    }
    /**
     * <code>repeated string mobiles = 8;</code>
     */
    public int getMobilesCount() {
      return mobiles_.size();
    }
    /**
     * <code>repeated string mobiles = 8;</code>
     */
    public java.lang.String getMobiles(int index) {
      return mobiles_.get(index);
    }
    /**
     * <code>repeated string mobiles = 8;</code>
     */
    public com.google.protobuf.ByteString
        getMobilesBytes(int index) {
      return mobiles_.getByteString(index);
    }

    public static final int PHONES_FIELD_NUMBER = 9;
    private com.google.protobuf.LazyStringList phones_;
    /**
     * <code>repeated string phones = 9;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPhonesList() {
      return phones_;
    }
    /**
     * <code>repeated string phones = 9;</code>
     */
    public int getPhonesCount() {
      return phones_.size();
    }
    /**
     * <code>repeated string phones = 9;</code>
     */
    public java.lang.String getPhones(int index) {
      return phones_.get(index);
    }
    /**
     * <code>repeated string phones = 9;</code>
     */
    public com.google.protobuf.ByteString
        getPhonesBytes(int index) {
      return phones_.getByteString(index);
    }

    public static final int EMAILS_FIELD_NUMBER = 10;
    private com.google.protobuf.LazyStringList emails_;
    /**
     * <code>repeated string emails = 10;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getEmailsList() {
      return emails_;
    }
    /**
     * <code>repeated string emails = 10;</code>
     */
    public int getEmailsCount() {
      return emails_.size();
    }
    /**
     * <code>repeated string emails = 10;</code>
     */
    public java.lang.String getEmails(int index) {
      return emails_.get(index);
    }
    /**
     * <code>repeated string emails = 10;</code>
     */
    public com.google.protobuf.ByteString
        getEmailsBytes(int index) {
      return emails_.getByteString(index);
    }

    public static final int BIRTHDAYS_FIELD_NUMBER = 11;
    private java.util.List<java.lang.Long> birthdays_;
    /**
     * <code>repeated int64 birthdays = 11;</code>
     */
    public java.util.List<java.lang.Long>
        getBirthdaysList() {
      return birthdays_;
    }
    /**
     * <code>repeated int64 birthdays = 11;</code>
     */
    public int getBirthdaysCount() {
      return birthdays_.size();
    }
    /**
     * <code>repeated int64 birthdays = 11;</code>
     */
    public long getBirthdays(int index) {
      return birthdays_.get(index);
    }
    private int birthdaysMemoizedSerializedSize = -1;

    public static final int ADDRESSES_FIELD_NUMBER = 12;
    private com.google.protobuf.LazyStringList addresses_;
    /**
     * <code>repeated string addresses = 12;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAddressesList() {
      return addresses_;
    }
    /**
     * <code>repeated string addresses = 12;</code>
     */
    public int getAddressesCount() {
      return addresses_.size();
    }
    /**
     * <code>repeated string addresses = 12;</code>
     */
    public java.lang.String getAddresses(int index) {
      return addresses_.get(index);
    }
    /**
     * <code>repeated string addresses = 12;</code>
     */
    public com.google.protobuf.ByteString
        getAddressesBytes(int index) {
      return addresses_.getByteString(index);
    }

    public static final int ACCOUNT_FIELD_NUMBER = 13;
    private volatile java.lang.Object account_;
    /**
     * <code>optional string account = 13;</code>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        account_ = s;
        return s;
      }
    }
    /**
     * <code>optional string account = 13;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYACCOUNTS_FIELD_NUMBER = 14;
    private java.util.List<com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount> payAccounts_;
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
     */
    public java.util.List<com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount> getPayAccountsList() {
      return payAccounts_;
    }
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
     */
    public java.util.List<? extends com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccountOrBuilder> 
        getPayAccountsOrBuilderList() {
      return payAccounts_;
    }
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
     */
    public int getPayAccountsCount() {
      return payAccounts_.size();
    }
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
     */
    public com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount getPayAccounts(int index) {
      return payAccounts_.get(index);
    }
    /**
     * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
     */
    public com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccountOrBuilder getPayAccountsOrBuilder(
        int index) {
      return payAccounts_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (baseDomain_ != null) {
        output.writeMessage(1, getBaseDomain());
      }
      if (id_ != 0L) {
        output.writeInt64(2, id_);
      }
      if (companyId_ != 0L) {
        output.writeInt64(3, companyId_);
      }
      if (platformId_ != 0L) {
        output.writeInt64(4, platformId_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, name_);
      }
      if (!getIdentityNosBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, identityNos_);
      }
      if (!getGenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, gender_);
      }
      for (int i = 0; i < mobiles_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, mobiles_.getRaw(i));
      }
      for (int i = 0; i < phones_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, phones_.getRaw(i));
      }
      for (int i = 0; i < emails_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, emails_.getRaw(i));
      }
      if (getBirthdaysList().size() > 0) {
        output.writeUInt32NoTag(90);
        output.writeUInt32NoTag(birthdaysMemoizedSerializedSize);
      }
      for (int i = 0; i < birthdays_.size(); i++) {
        output.writeInt64NoTag(birthdays_.get(i));
      }
      for (int i = 0; i < addresses_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, addresses_.getRaw(i));
      }
      if (!getAccountBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, account_);
      }
      for (int i = 0; i < payAccounts_.size(); i++) {
        output.writeMessage(14, payAccounts_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (baseDomain_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBaseDomain());
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, id_);
      }
      if (companyId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, companyId_);
      }
      if (platformId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, platformId_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, name_);
      }
      if (!getIdentityNosBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, identityNos_);
      }
      if (!getGenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, gender_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < mobiles_.size(); i++) {
          dataSize += computeStringSizeNoTag(mobiles_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMobilesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < phones_.size(); i++) {
          dataSize += computeStringSizeNoTag(phones_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPhonesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < emails_.size(); i++) {
          dataSize += computeStringSizeNoTag(emails_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getEmailsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < birthdays_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(birthdays_.get(i));
        }
        size += dataSize;
        if (!getBirthdaysList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        birthdaysMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < addresses_.size(); i++) {
          dataSize += computeStringSizeNoTag(addresses_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAddressesList().size();
      }
      if (!getAccountBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, account_);
      }
      for (int i = 0; i < payAccounts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(14, payAccounts_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer)) {
        return super.equals(obj);
      }
      com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer other = (com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer) obj;

      boolean result = true;
      result = result && (hasBaseDomain() == other.hasBaseDomain());
      if (hasBaseDomain()) {
        result = result && getBaseDomain()
            .equals(other.getBaseDomain());
      }
      result = result && (getId()
          == other.getId());
      result = result && (getCompanyId()
          == other.getCompanyId());
      result = result && (getPlatformId()
          == other.getPlatformId());
      result = result && getName()
          .equals(other.getName());
      result = result && getIdentityNos()
          .equals(other.getIdentityNos());
      result = result && getGender()
          .equals(other.getGender());
      result = result && getMobilesList()
          .equals(other.getMobilesList());
      result = result && getPhonesList()
          .equals(other.getPhonesList());
      result = result && getEmailsList()
          .equals(other.getEmailsList());
      result = result && getBirthdaysList()
          .equals(other.getBirthdaysList());
      result = result && getAddressesList()
          .equals(other.getAddressesList());
      result = result && getAccount()
          .equals(other.getAccount());
      result = result && getPayAccountsList()
          .equals(other.getPayAccountsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasBaseDomain()) {
        hash = (37 * hash) + BASEDOMAIN_FIELD_NUMBER;
        hash = (53 * hash) + getBaseDomain().hashCode();
      }
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + COMPANYID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCompanyId());
      hash = (37 * hash) + PLATFORMID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlatformId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + IDENTITYNOS_FIELD_NUMBER;
      hash = (53 * hash) + getIdentityNos().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getGender().hashCode();
      if (getMobilesCount() > 0) {
        hash = (37 * hash) + MOBILES_FIELD_NUMBER;
        hash = (53 * hash) + getMobilesList().hashCode();
      }
      if (getPhonesCount() > 0) {
        hash = (37 * hash) + PHONES_FIELD_NUMBER;
        hash = (53 * hash) + getPhonesList().hashCode();
      }
      if (getEmailsCount() > 0) {
        hash = (37 * hash) + EMAILS_FIELD_NUMBER;
        hash = (53 * hash) + getEmailsList().hashCode();
      }
      if (getBirthdaysCount() > 0) {
        hash = (37 * hash) + BIRTHDAYS_FIELD_NUMBER;
        hash = (53 * hash) + getBirthdaysList().hashCode();
      }
      if (getAddressesCount() > 0) {
        hash = (37 * hash) + ADDRESSES_FIELD_NUMBER;
        hash = (53 * hash) + getAddressesList().hashCode();
      }
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
      if (getPayAccountsCount() > 0) {
        hash = (37 * hash) + PAYACCOUNTS_FIELD_NUMBER;
        hash = (53 * hash) + getPayAccountsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.fx.productization.datanormalizer.domain.core.dto.Customer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.fx.productization.datanormalizer.domain.core.dto.Customer)
        com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.CustomerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_Customer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_Customer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer.class, com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer.Builder.class);
      }

      // Construct using com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPayAccountsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (baseDomainBuilder_ == null) {
          baseDomain_ = null;
        } else {
          baseDomain_ = null;
          baseDomainBuilder_ = null;
        }
        id_ = 0L;

        companyId_ = 0L;

        platformId_ = 0L;

        name_ = "";

        identityNos_ = "";

        gender_ = "";

        mobiles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        emails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        birthdays_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000400);
        addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000800);
        account_ = "";

        if (payAccountsBuilder_ == null) {
          payAccounts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00002000);
        } else {
          payAccountsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_Customer_descriptor;
      }

      public com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer getDefaultInstanceForType() {
        return com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer.getDefaultInstance();
      }

      public com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer build() {
        com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer buildPartial() {
        com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer result = new com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (baseDomainBuilder_ == null) {
          result.baseDomain_ = baseDomain_;
        } else {
          result.baseDomain_ = baseDomainBuilder_.build();
        }
        result.id_ = id_;
        result.companyId_ = companyId_;
        result.platformId_ = platformId_;
        result.name_ = name_;
        result.identityNos_ = identityNos_;
        result.gender_ = gender_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          mobiles_ = mobiles_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.mobiles_ = mobiles_;
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          phones_ = phones_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.phones_ = phones_;
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          emails_ = emails_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.emails_ = emails_;
        if (((bitField0_ & 0x00000400) == 0x00000400)) {
          birthdays_ = java.util.Collections.unmodifiableList(birthdays_);
          bitField0_ = (bitField0_ & ~0x00000400);
        }
        result.birthdays_ = birthdays_;
        if (((bitField0_ & 0x00000800) == 0x00000800)) {
          addresses_ = addresses_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000800);
        }
        result.addresses_ = addresses_;
        result.account_ = account_;
        if (payAccountsBuilder_ == null) {
          if (((bitField0_ & 0x00002000) == 0x00002000)) {
            payAccounts_ = java.util.Collections.unmodifiableList(payAccounts_);
            bitField0_ = (bitField0_ & ~0x00002000);
          }
          result.payAccounts_ = payAccounts_;
        } else {
          result.payAccounts_ = payAccountsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer) {
          return mergeFrom((com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer other) {
        if (other == com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer.getDefaultInstance()) return this;
        if (other.hasBaseDomain()) {
          mergeBaseDomain(other.getBaseDomain());
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getCompanyId() != 0L) {
          setCompanyId(other.getCompanyId());
        }
        if (other.getPlatformId() != 0L) {
          setPlatformId(other.getPlatformId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getIdentityNos().isEmpty()) {
          identityNos_ = other.identityNos_;
          onChanged();
        }
        if (!other.getGender().isEmpty()) {
          gender_ = other.gender_;
          onChanged();
        }
        if (!other.mobiles_.isEmpty()) {
          if (mobiles_.isEmpty()) {
            mobiles_ = other.mobiles_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureMobilesIsMutable();
            mobiles_.addAll(other.mobiles_);
          }
          onChanged();
        }
        if (!other.phones_.isEmpty()) {
          if (phones_.isEmpty()) {
            phones_ = other.phones_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensurePhonesIsMutable();
            phones_.addAll(other.phones_);
          }
          onChanged();
        }
        if (!other.emails_.isEmpty()) {
          if (emails_.isEmpty()) {
            emails_ = other.emails_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureEmailsIsMutable();
            emails_.addAll(other.emails_);
          }
          onChanged();
        }
        if (!other.birthdays_.isEmpty()) {
          if (birthdays_.isEmpty()) {
            birthdays_ = other.birthdays_;
            bitField0_ = (bitField0_ & ~0x00000400);
          } else {
            ensureBirthdaysIsMutable();
            birthdays_.addAll(other.birthdays_);
          }
          onChanged();
        }
        if (!other.addresses_.isEmpty()) {
          if (addresses_.isEmpty()) {
            addresses_ = other.addresses_;
            bitField0_ = (bitField0_ & ~0x00000800);
          } else {
            ensureAddressesIsMutable();
            addresses_.addAll(other.addresses_);
          }
          onChanged();
        }
        if (!other.getAccount().isEmpty()) {
          account_ = other.account_;
          onChanged();
        }
        if (payAccountsBuilder_ == null) {
          if (!other.payAccounts_.isEmpty()) {
            if (payAccounts_.isEmpty()) {
              payAccounts_ = other.payAccounts_;
              bitField0_ = (bitField0_ & ~0x00002000);
            } else {
              ensurePayAccountsIsMutable();
              payAccounts_.addAll(other.payAccounts_);
            }
            onChanged();
          }
        } else {
          if (!other.payAccounts_.isEmpty()) {
            if (payAccountsBuilder_.isEmpty()) {
              payAccountsBuilder_.dispose();
              payAccountsBuilder_ = null;
              payAccounts_ = other.payAccounts_;
              bitField0_ = (bitField0_ & ~0x00002000);
              payAccountsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPayAccountsFieldBuilder() : null;
            } else {
              payAccountsBuilder_.addAllMessages(other.payAccounts_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain baseDomain_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain, com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.Builder, com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomainOrBuilder> baseDomainBuilder_;
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
       */
      public boolean hasBaseDomain() {
        return baseDomainBuilder_ != null || baseDomain_ != null;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain getBaseDomain() {
        if (baseDomainBuilder_ == null) {
          return baseDomain_ == null ? com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.getDefaultInstance() : baseDomain_;
        } else {
          return baseDomainBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
       */
      public Builder setBaseDomain(com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain value) {
        if (baseDomainBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseDomain_ = value;
          onChanged();
        } else {
          baseDomainBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
       */
      public Builder setBaseDomain(
          com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.Builder builderForValue) {
        if (baseDomainBuilder_ == null) {
          baseDomain_ = builderForValue.build();
          onChanged();
        } else {
          baseDomainBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
       */
      public Builder mergeBaseDomain(com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain value) {
        if (baseDomainBuilder_ == null) {
          if (baseDomain_ != null) {
            baseDomain_ =
              com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.newBuilder(baseDomain_).mergeFrom(value).buildPartial();
          } else {
            baseDomain_ = value;
          }
          onChanged();
        } else {
          baseDomainBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
       */
      public Builder clearBaseDomain() {
        if (baseDomainBuilder_ == null) {
          baseDomain_ = null;
          onChanged();
        } else {
          baseDomain_ = null;
          baseDomainBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.Builder getBaseDomainBuilder() {
        
        onChanged();
        return getBaseDomainFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomainOrBuilder getBaseDomainOrBuilder() {
        if (baseDomainBuilder_ != null) {
          return baseDomainBuilder_.getMessageOrBuilder();
        } else {
          return baseDomain_ == null ?
              com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.getDefaultInstance() : baseDomain_;
        }
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.BaseDomain baseDomain = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain, com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.Builder, com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomainOrBuilder> 
          getBaseDomainFieldBuilder() {
        if (baseDomainBuilder_ == null) {
          baseDomainBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain, com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomain.Builder, com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.BaseDomainOrBuilder>(
                  getBaseDomain(),
                  getParentForChildren(),
                  isClean());
          baseDomain_ = null;
        }
        return baseDomainBuilder_;
      }

      private long id_ ;
      /**
       * <code>optional int64 id = 2;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 2;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 2;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long companyId_ ;
      /**
       * <code>optional int64 companyId = 3;</code>
       */
      public long getCompanyId() {
        return companyId_;
      }
      /**
       * <code>optional int64 companyId = 3;</code>
       */
      public Builder setCompanyId(long value) {
        
        companyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 companyId = 3;</code>
       */
      public Builder clearCompanyId() {
        
        companyId_ = 0L;
        onChanged();
        return this;
      }

      private long platformId_ ;
      /**
       * <code>optional int64 platformId = 4;</code>
       */
      public long getPlatformId() {
        return platformId_;
      }
      /**
       * <code>optional int64 platformId = 4;</code>
       */
      public Builder setPlatformId(long value) {
        
        platformId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 platformId = 4;</code>
       */
      public Builder clearPlatformId() {
        
        platformId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 5;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 5;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 5;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 5;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object identityNos_ = "";
      /**
       * <code>optional string identityNos = 6;</code>
       */
      public java.lang.String getIdentityNos() {
        java.lang.Object ref = identityNos_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          identityNos_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string identityNos = 6;</code>
       */
      public com.google.protobuf.ByteString
          getIdentityNosBytes() {
        java.lang.Object ref = identityNos_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          identityNos_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string identityNos = 6;</code>
       */
      public Builder setIdentityNos(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        identityNos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string identityNos = 6;</code>
       */
      public Builder clearIdentityNos() {
        
        identityNos_ = getDefaultInstance().getIdentityNos();
        onChanged();
        return this;
      }
      /**
       * <code>optional string identityNos = 6;</code>
       */
      public Builder setIdentityNosBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        identityNos_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gender_ = "";
      /**
       * <code>optional string gender = 7;</code>
       */
      public java.lang.String getGender() {
        java.lang.Object ref = gender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string gender = 7;</code>
       */
      public com.google.protobuf.ByteString
          getGenderBytes() {
        java.lang.Object ref = gender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string gender = 7;</code>
       */
      public Builder setGender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string gender = 7;</code>
       */
      public Builder clearGender() {
        
        gender_ = getDefaultInstance().getGender();
        onChanged();
        return this;
      }
      /**
       * <code>optional string gender = 7;</code>
       */
      public Builder setGenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gender_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList mobiles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMobilesIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          mobiles_ = new com.google.protobuf.LazyStringArrayList(mobiles_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <code>repeated string mobiles = 8;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getMobilesList() {
        return mobiles_.getUnmodifiableView();
      }
      /**
       * <code>repeated string mobiles = 8;</code>
       */
      public int getMobilesCount() {
        return mobiles_.size();
      }
      /**
       * <code>repeated string mobiles = 8;</code>
       */
      public java.lang.String getMobiles(int index) {
        return mobiles_.get(index);
      }
      /**
       * <code>repeated string mobiles = 8;</code>
       */
      public com.google.protobuf.ByteString
          getMobilesBytes(int index) {
        return mobiles_.getByteString(index);
      }
      /**
       * <code>repeated string mobiles = 8;</code>
       */
      public Builder setMobiles(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMobilesIsMutable();
        mobiles_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mobiles = 8;</code>
       */
      public Builder addMobiles(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMobilesIsMutable();
        mobiles_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mobiles = 8;</code>
       */
      public Builder addAllMobiles(
          java.lang.Iterable<java.lang.String> values) {
        ensureMobilesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mobiles_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mobiles = 8;</code>
       */
      public Builder clearMobiles() {
        mobiles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mobiles = 8;</code>
       */
      public Builder addMobilesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureMobilesIsMutable();
        mobiles_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePhonesIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          phones_ = new com.google.protobuf.LazyStringArrayList(phones_);
          bitField0_ |= 0x00000100;
         }
      }
      /**
       * <code>repeated string phones = 9;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPhonesList() {
        return phones_.getUnmodifiableView();
      }
      /**
       * <code>repeated string phones = 9;</code>
       */
      public int getPhonesCount() {
        return phones_.size();
      }
      /**
       * <code>repeated string phones = 9;</code>
       */
      public java.lang.String getPhones(int index) {
        return phones_.get(index);
      }
      /**
       * <code>repeated string phones = 9;</code>
       */
      public com.google.protobuf.ByteString
          getPhonesBytes(int index) {
        return phones_.getByteString(index);
      }
      /**
       * <code>repeated string phones = 9;</code>
       */
      public Builder setPhones(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhonesIsMutable();
        phones_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phones = 9;</code>
       */
      public Builder addPhones(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhonesIsMutable();
        phones_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phones = 9;</code>
       */
      public Builder addAllPhones(
          java.lang.Iterable<java.lang.String> values) {
        ensurePhonesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phones_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phones = 9;</code>
       */
      public Builder clearPhones() {
        phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phones = 9;</code>
       */
      public Builder addPhonesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePhonesIsMutable();
        phones_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList emails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureEmailsIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          emails_ = new com.google.protobuf.LazyStringArrayList(emails_);
          bitField0_ |= 0x00000200;
         }
      }
      /**
       * <code>repeated string emails = 10;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getEmailsList() {
        return emails_.getUnmodifiableView();
      }
      /**
       * <code>repeated string emails = 10;</code>
       */
      public int getEmailsCount() {
        return emails_.size();
      }
      /**
       * <code>repeated string emails = 10;</code>
       */
      public java.lang.String getEmails(int index) {
        return emails_.get(index);
      }
      /**
       * <code>repeated string emails = 10;</code>
       */
      public com.google.protobuf.ByteString
          getEmailsBytes(int index) {
        return emails_.getByteString(index);
      }
      /**
       * <code>repeated string emails = 10;</code>
       */
      public Builder setEmails(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEmailsIsMutable();
        emails_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string emails = 10;</code>
       */
      public Builder addEmails(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEmailsIsMutable();
        emails_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string emails = 10;</code>
       */
      public Builder addAllEmails(
          java.lang.Iterable<java.lang.String> values) {
        ensureEmailsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, emails_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string emails = 10;</code>
       */
      public Builder clearEmails() {
        emails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string emails = 10;</code>
       */
      public Builder addEmailsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureEmailsIsMutable();
        emails_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Long> birthdays_ = java.util.Collections.emptyList();
      private void ensureBirthdaysIsMutable() {
        if (!((bitField0_ & 0x00000400) == 0x00000400)) {
          birthdays_ = new java.util.ArrayList<java.lang.Long>(birthdays_);
          bitField0_ |= 0x00000400;
         }
      }
      /**
       * <code>repeated int64 birthdays = 11;</code>
       */
      public java.util.List<java.lang.Long>
          getBirthdaysList() {
        return java.util.Collections.unmodifiableList(birthdays_);
      }
      /**
       * <code>repeated int64 birthdays = 11;</code>
       */
      public int getBirthdaysCount() {
        return birthdays_.size();
      }
      /**
       * <code>repeated int64 birthdays = 11;</code>
       */
      public long getBirthdays(int index) {
        return birthdays_.get(index);
      }
      /**
       * <code>repeated int64 birthdays = 11;</code>
       */
      public Builder setBirthdays(
          int index, long value) {
        ensureBirthdaysIsMutable();
        birthdays_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 birthdays = 11;</code>
       */
      public Builder addBirthdays(long value) {
        ensureBirthdaysIsMutable();
        birthdays_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 birthdays = 11;</code>
       */
      public Builder addAllBirthdays(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureBirthdaysIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, birthdays_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 birthdays = 11;</code>
       */
      public Builder clearBirthdays() {
        birthdays_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAddressesIsMutable() {
        if (!((bitField0_ & 0x00000800) == 0x00000800)) {
          addresses_ = new com.google.protobuf.LazyStringArrayList(addresses_);
          bitField0_ |= 0x00000800;
         }
      }
      /**
       * <code>repeated string addresses = 12;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAddressesList() {
        return addresses_.getUnmodifiableView();
      }
      /**
       * <code>repeated string addresses = 12;</code>
       */
      public int getAddressesCount() {
        return addresses_.size();
      }
      /**
       * <code>repeated string addresses = 12;</code>
       */
      public java.lang.String getAddresses(int index) {
        return addresses_.get(index);
      }
      /**
       * <code>repeated string addresses = 12;</code>
       */
      public com.google.protobuf.ByteString
          getAddressesBytes(int index) {
        return addresses_.getByteString(index);
      }
      /**
       * <code>repeated string addresses = 12;</code>
       */
      public Builder setAddresses(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressesIsMutable();
        addresses_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 12;</code>
       */
      public Builder addAddresses(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressesIsMutable();
        addresses_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 12;</code>
       */
      public Builder addAllAddresses(
          java.lang.Iterable<java.lang.String> values) {
        ensureAddressesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, addresses_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 12;</code>
       */
      public Builder clearAddresses() {
        addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000800);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 12;</code>
       */
      public Builder addAddressesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAddressesIsMutable();
        addresses_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object account_ = "";
      /**
       * <code>optional string account = 13;</code>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string account = 13;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string account = 13;</code>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string account = 13;</code>
       */
      public Builder clearAccount() {
        
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>optional string account = 13;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        account_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount> payAccounts_ =
        java.util.Collections.emptyList();
      private void ensurePayAccountsIsMutable() {
        if (!((bitField0_ & 0x00002000) == 0x00002000)) {
          payAccounts_ = new java.util.ArrayList<com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount>(payAccounts_);
          bitField0_ |= 0x00002000;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount, com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.Builder, com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccountOrBuilder> payAccountsBuilder_;

      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
       */
      public java.util.List<com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount> getPayAccountsList() {
        if (payAccountsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(payAccounts_);
        } else {
          return payAccountsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
       */
      public int getPayAccountsCount() {
        if (payAccountsBuilder_ == null) {
          return payAccounts_.size();
        } else {
          return payAccountsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount getPayAccounts(int index) {
        if (payAccountsBuilder_ == null) {
          return payAccounts_.get(index);
        } else {
          return payAccountsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
       */
      public Builder setPayAccounts(
          int index, com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount value) {
        if (payAccountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePayAccountsIsMutable();
          payAccounts_.set(index, value);
          onChanged();
        } else {
          payAccountsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
       */
      public Builder setPayAccounts(
          int index, com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.Builder builderForValue) {
        if (payAccountsBuilder_ == null) {
          ensurePayAccountsIsMutable();
          payAccounts_.set(index, builderForValue.build());
          onChanged();
        } else {
          payAccountsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
       */
      public Builder addPayAccounts(com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount value) {
        if (payAccountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePayAccountsIsMutable();
          payAccounts_.add(value);
          onChanged();
        } else {
          payAccountsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
       */
      public Builder addPayAccounts(
          int index, com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount value) {
        if (payAccountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePayAccountsIsMutable();
          payAccounts_.add(index, value);
          onChanged();
        } else {
          payAccountsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
       */
      public Builder addPayAccounts(
          com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.Builder builderForValue) {
        if (payAccountsBuilder_ == null) {
          ensurePayAccountsIsMutable();
          payAccounts_.add(builderForValue.build());
          onChanged();
        } else {
          payAccountsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
       */
      public Builder addPayAccounts(
          int index, com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.Builder builderForValue) {
        if (payAccountsBuilder_ == null) {
          ensurePayAccountsIsMutable();
          payAccounts_.add(index, builderForValue.build());
          onChanged();
        } else {
          payAccountsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
       */
      public Builder addAllPayAccounts(
          java.lang.Iterable<? extends com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount> values) {
        if (payAccountsBuilder_ == null) {
          ensurePayAccountsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, payAccounts_);
          onChanged();
        } else {
          payAccountsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
       */
      public Builder clearPayAccounts() {
        if (payAccountsBuilder_ == null) {
          payAccounts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00002000);
          onChanged();
        } else {
          payAccountsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
       */
      public Builder removePayAccounts(int index) {
        if (payAccountsBuilder_ == null) {
          ensurePayAccountsIsMutable();
          payAccounts_.remove(index);
          onChanged();
        } else {
          payAccountsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.Builder getPayAccountsBuilder(
          int index) {
        return getPayAccountsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccountOrBuilder getPayAccountsOrBuilder(
          int index) {
        if (payAccountsBuilder_ == null) {
          return payAccounts_.get(index);  } else {
          return payAccountsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
       */
      public java.util.List<? extends com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccountOrBuilder> 
           getPayAccountsOrBuilderList() {
        if (payAccountsBuilder_ != null) {
          return payAccountsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(payAccounts_);
        }
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.Builder addPayAccountsBuilder() {
        return getPayAccountsFieldBuilder().addBuilder(
            com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.getDefaultInstance());
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.Builder addPayAccountsBuilder(
          int index) {
        return getPayAccountsFieldBuilder().addBuilder(
            index, com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.getDefaultInstance());
      }
      /**
       * <code>repeated .com.fx.productization.datanormalizer.domain.core.dto.PayAccount payAccounts = 14;</code>
       */
      public java.util.List<com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.Builder> 
           getPayAccountsBuilderList() {
        return getPayAccountsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount, com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.Builder, com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccountOrBuilder> 
          getPayAccountsFieldBuilder() {
        if (payAccountsBuilder_ == null) {
          payAccountsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount, com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.Builder, com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccountOrBuilder>(
                  payAccounts_,
                  ((bitField0_ & 0x00002000) == 0x00002000),
                  getParentForChildren(),
                  isClean());
          payAccounts_ = null;
        }
        return payAccountsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.fx.productization.datanormalizer.domain.core.dto.Customer)
    }

    // @@protoc_insertion_point(class_scope:com.fx.productization.datanormalizer.domain.core.dto.Customer)
    private static final com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer();
    }

    public static com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Customer>
        PARSER = new com.google.protobuf.AbstractParser<Customer>() {
      public Customer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Customer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Customer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Customer> getParserForType() {
      return PARSER;
    }

    public com.fx.productization.datanormalizer.domain.core.dto.CustomerOuterClass.Customer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fx_productization_datanormalizer_domain_core_dto_Customer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fx_productization_datanormalizer_domain_core_dto_Customer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Customer.proto\0224com.fx.productization." +
      "datanormalizer.domain.core.dto\032\020BaseDoma" +
      "in.proto\032\020PayAccount.proto\"\205\003\n\010Customer\022" +
      "T\n\nbaseDomain\030\001 \001(\0132@.com.fx.productizat" +
      "ion.datanormalizer.domain.core.dto.BaseD" +
      "omain\022\n\n\002id\030\002 \001(\003\022\021\n\tcompanyId\030\003 \001(\003\022\022\n\n" +
      "platformId\030\004 \001(\003\022\014\n\004name\030\005 \001(\t\022\023\n\013identi" +
      "tyNos\030\006 \001(\t\022\016\n\006gender\030\007 \001(\t\022\017\n\007mobiles\030\010" +
      " \003(\t\022\016\n\006phones\030\t \003(\t\022\016\n\006emails\030\n \003(\t\022\021\n\t" +
      "birthdays\030\013 \003(\003\022\021\n\taddresses\030\014 \003(\t\022\017\n\007ac",
      "count\030\r \001(\t\022U\n\013payAccounts\030\016 \003(\0132@.com.f" +
      "x.productization.datanormalizer.domain.c" +
      "ore.dto.PayAccountb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.getDescriptor(),
          com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_fx_productization_datanormalizer_domain_core_dto_Customer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fx_productization_datanormalizer_domain_core_dto_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fx_productization_datanormalizer_domain_core_dto_Customer_descriptor,
        new java.lang.String[] { "BaseDomain", "Id", "CompanyId", "PlatformId", "Name", "IdentityNos", "Gender", "Mobiles", "Phones", "Emails", "Birthdays", "Addresses", "Account", "PayAccounts", });
    com.fx.productization.datanormalizer.domain.core.dto.BaseDomainOuterClass.getDescriptor();
    com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
