// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemCodeType.proto

package com.fx.productization.datanormalizer.domain.core.dto;

public final class ItemCodeTypeOuterClass {
  private ItemCodeTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.fx.productization.datanormalizer.domain.core.dto.ItemCodeType}
   */
  public enum ItemCodeType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SixNineCode = 0;</code>
     */
    SixNineCode(0),
    /**
     * <code>QRCode = 1;</code>
     */
    QRCode(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SixNineCode = 0;</code>
     */
    public static final int SixNineCode_VALUE = 0;
    /**
     * <code>QRCode = 1;</code>
     */
    public static final int QRCode_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ItemCodeType valueOf(int value) {
      return forNumber(value);
    }

    public static ItemCodeType forNumber(int value) {
      switch (value) {
        case 0: return SixNineCode;
        case 1: return QRCode;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ItemCodeType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ItemCodeType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ItemCodeType>() {
            public ItemCodeType findValueByNumber(int number) {
              return ItemCodeType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.fx.productization.datanormalizer.domain.core.dto.ItemCodeTypeOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final ItemCodeType[] VALUES = values();

    public static ItemCodeType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ItemCodeType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.fx.productization.datanormalizer.domain.core.dto.ItemCodeType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ItemCodeType.proto\0224com.fx.productizat" +
      "ion.datanormalizer.domain.core.dto*+\n\014It" +
      "emCodeType\022\017\n\013SixNineCode\020\000\022\n\n\006QRCode\020\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
