// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PayAccount.proto

package com.fx.productization.datanormalizer.domain.core.dto;

public final class PayAccountOuterClass {
  private PayAccountOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PayAccountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.fx.productization.datanormalizer.domain.core.dto.PayAccount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string account = 1;</code>
     */
    java.lang.String getAccount();
    /**
     * <code>optional string account = 1;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.PayType type = 2;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.PayType type = 2;</code>
     */
    com.fx.productization.datanormalizer.domain.core.dto.PayTypeOuterClass.PayType getType();
  }
  /**
   * Protobuf type {@code com.fx.productization.datanormalizer.domain.core.dto.PayAccount}
   */
  public  static final class PayAccount extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.fx.productization.datanormalizer.domain.core.dto.PayAccount)
      PayAccountOrBuilder {
    // Use PayAccount.newBuilder() to construct.
    private PayAccount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PayAccount() {
      account_ = "";
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PayAccount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              account_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_PayAccount_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_PayAccount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.class, com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.Builder.class);
    }

    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private volatile java.lang.Object account_;
    /**
     * <code>optional string account = 1;</code>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        account_ = s;
        return s;
      }
    }
    /**
     * <code>optional string account = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.PayType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.PayType type = 2;</code>
     */
    public com.fx.productization.datanormalizer.domain.core.dto.PayTypeOuterClass.PayType getType() {
      com.fx.productization.datanormalizer.domain.core.dto.PayTypeOuterClass.PayType result = com.fx.productization.datanormalizer.domain.core.dto.PayTypeOuterClass.PayType.valueOf(type_);
      return result == null ? com.fx.productization.datanormalizer.domain.core.dto.PayTypeOuterClass.PayType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAccountBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, account_);
      }
      if (type_ != com.fx.productization.datanormalizer.domain.core.dto.PayTypeOuterClass.PayType.Alipay.getNumber()) {
        output.writeEnum(2, type_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAccountBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, account_);
      }
      if (type_ != com.fx.productization.datanormalizer.domain.core.dto.PayTypeOuterClass.PayType.Alipay.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount)) {
        return super.equals(obj);
      }
      com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount other = (com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount) obj;

      boolean result = true;
      result = result && getAccount()
          .equals(other.getAccount());
      result = result && type_ == other.type_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.fx.productization.datanormalizer.domain.core.dto.PayAccount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.fx.productization.datanormalizer.domain.core.dto.PayAccount)
        com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_PayAccount_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_PayAccount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.class, com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.Builder.class);
      }

      // Construct using com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        account_ = "";

        type_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_PayAccount_descriptor;
      }

      public com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount getDefaultInstanceForType() {
        return com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.getDefaultInstance();
      }

      public com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount build() {
        com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount buildPartial() {
        com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount result = new com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount(this);
        result.account_ = account_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount) {
          return mergeFrom((com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount other) {
        if (other == com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount.getDefaultInstance()) return this;
        if (!other.getAccount().isEmpty()) {
          account_ = other.account_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object account_ = "";
      /**
       * <code>optional string account = 1;</code>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string account = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string account = 1;</code>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string account = 1;</code>
       */
      public Builder clearAccount() {
        
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>optional string account = 1;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        account_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.PayType type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.PayType type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.PayType type = 2;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.PayTypeOuterClass.PayType getType() {
        com.fx.productization.datanormalizer.domain.core.dto.PayTypeOuterClass.PayType result = com.fx.productization.datanormalizer.domain.core.dto.PayTypeOuterClass.PayType.valueOf(type_);
        return result == null ? com.fx.productization.datanormalizer.domain.core.dto.PayTypeOuterClass.PayType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.PayType type = 2;</code>
       */
      public Builder setType(com.fx.productization.datanormalizer.domain.core.dto.PayTypeOuterClass.PayType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.PayType type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.fx.productization.datanormalizer.domain.core.dto.PayAccount)
    }

    // @@protoc_insertion_point(class_scope:com.fx.productization.datanormalizer.domain.core.dto.PayAccount)
    private static final com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount();
    }

    public static com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PayAccount>
        PARSER = new com.google.protobuf.AbstractParser<PayAccount>() {
      public PayAccount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PayAccount(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PayAccount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PayAccount> getParserForType() {
      return PARSER;
    }

    public com.fx.productization.datanormalizer.domain.core.dto.PayAccountOuterClass.PayAccount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fx_productization_datanormalizer_domain_core_dto_PayAccount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fx_productization_datanormalizer_domain_core_dto_PayAccount_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020PayAccount.proto\0224com.fx.productizatio" +
      "n.datanormalizer.domain.core.dto\032\rPayTyp" +
      "e.proto\"j\n\nPayAccount\022\017\n\007account\030\001 \001(\t\022K" +
      "\n\004type\030\002 \001(\0162=.com.fx.productization.dat" +
      "anormalizer.domain.core.dto.PayTypeb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fx.productization.datanormalizer.domain.core.dto.PayTypeOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_fx_productization_datanormalizer_domain_core_dto_PayAccount_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fx_productization_datanormalizer_domain_core_dto_PayAccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fx_productization_datanormalizer_domain_core_dto_PayAccount_descriptor,
        new java.lang.String[] { "Account", "Type", });
    com.fx.productization.datanormalizer.domain.core.dto.PayTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
