// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PayType.proto

package com.fx.productization.datanormalizer.domain.core.dto;

public final class PayTypeOuterClass {
  private PayTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.fx.productization.datanormalizer.domain.core.dto.PayType}
   */
  public enum PayType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Alipay = 0;</code>
     */
    Alipay(0),
    /**
     * <code>CreditCard = 1;</code>
     */
    CreditCard(1),
    /**
     * <code>WeChat = 2;</code>
     */
    WeChat(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Alipay = 0;</code>
     */
    public static final int Alipay_VALUE = 0;
    /**
     * <code>CreditCard = 1;</code>
     */
    public static final int CreditCard_VALUE = 1;
    /**
     * <code>WeChat = 2;</code>
     */
    public static final int WeChat_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayType valueOf(int value) {
      return forNumber(value);
    }

    public static PayType forNumber(int value) {
      switch (value) {
        case 0: return Alipay;
        case 1: return CreditCard;
        case 2: return WeChat;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PayType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PayType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PayType>() {
            public PayType findValueByNumber(int number) {
              return PayType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.fx.productization.datanormalizer.domain.core.dto.PayTypeOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final PayType[] VALUES = values();

    public static PayType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PayType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.fx.productization.datanormalizer.domain.core.dto.PayType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rPayType.proto\0224com.fx.productization.d" +
      "atanormalizer.domain.core.dto*1\n\007PayType" +
      "\022\n\n\006Alipay\020\000\022\016\n\nCreditCard\020\001\022\n\n\006WeChat\020\002" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
