// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UnifyItemCode.proto

package com.fx.productization.datanormalizer.domain.core.dto;

public final class UnifyItemCodeOuterClass {
  private UnifyItemCodeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UnifyItemCodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.ItemCodeType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.ItemCodeType type = 1;</code>
     */
    com.fx.productization.datanormalizer.domain.core.dto.ItemCodeTypeOuterClass.ItemCodeType getType();

    /**
     * <code>optional string itemCode = 2;</code>
     */
    java.lang.String getItemCode();
    /**
     * <code>optional string itemCode = 2;</code>
     */
    com.google.protobuf.ByteString
        getItemCodeBytes();
  }
  /**
   * Protobuf type {@code com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCode}
   */
  public  static final class UnifyItemCode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCode)
      UnifyItemCodeOrBuilder {
    // Use UnifyItemCode.newBuilder() to construct.
    private UnifyItemCode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UnifyItemCode() {
      type_ = 0;
      itemCode_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UnifyItemCode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              itemCode_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_UnifyItemCode_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_UnifyItemCode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode.class, com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.ItemCodeType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.ItemCodeType type = 1;</code>
     */
    public com.fx.productization.datanormalizer.domain.core.dto.ItemCodeTypeOuterClass.ItemCodeType getType() {
      com.fx.productization.datanormalizer.domain.core.dto.ItemCodeTypeOuterClass.ItemCodeType result = com.fx.productization.datanormalizer.domain.core.dto.ItemCodeTypeOuterClass.ItemCodeType.valueOf(type_);
      return result == null ? com.fx.productization.datanormalizer.domain.core.dto.ItemCodeTypeOuterClass.ItemCodeType.UNRECOGNIZED : result;
    }

    public static final int ITEMCODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object itemCode_;
    /**
     * <code>optional string itemCode = 2;</code>
     */
    public java.lang.String getItemCode() {
      java.lang.Object ref = itemCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        itemCode_ = s;
        return s;
      }
    }
    /**
     * <code>optional string itemCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getItemCodeBytes() {
      java.lang.Object ref = itemCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.fx.productization.datanormalizer.domain.core.dto.ItemCodeTypeOuterClass.ItemCodeType.SixNineCode.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getItemCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, itemCode_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.fx.productization.datanormalizer.domain.core.dto.ItemCodeTypeOuterClass.ItemCodeType.SixNineCode.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getItemCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, itemCode_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode)) {
        return super.equals(obj);
      }
      com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode other = (com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getItemCode()
          .equals(other.getItemCode());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + ITEMCODE_FIELD_NUMBER;
      hash = (53 * hash) + getItemCode().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCode)
        com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_UnifyItemCode_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_UnifyItemCode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode.class, com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode.Builder.class);
      }

      // Construct using com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        itemCode_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.internal_static_com_fx_productization_datanormalizer_domain_core_dto_UnifyItemCode_descriptor;
      }

      public com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode getDefaultInstanceForType() {
        return com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode.getDefaultInstance();
      }

      public com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode build() {
        com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode buildPartial() {
        com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode result = new com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode(this);
        result.type_ = type_;
        result.itemCode_ = itemCode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode) {
          return mergeFrom((com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode other) {
        if (other == com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getItemCode().isEmpty()) {
          itemCode_ = other.itemCode_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.ItemCodeType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.ItemCodeType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.ItemCodeType type = 1;</code>
       */
      public com.fx.productization.datanormalizer.domain.core.dto.ItemCodeTypeOuterClass.ItemCodeType getType() {
        com.fx.productization.datanormalizer.domain.core.dto.ItemCodeTypeOuterClass.ItemCodeType result = com.fx.productization.datanormalizer.domain.core.dto.ItemCodeTypeOuterClass.ItemCodeType.valueOf(type_);
        return result == null ? com.fx.productization.datanormalizer.domain.core.dto.ItemCodeTypeOuterClass.ItemCodeType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.ItemCodeType type = 1;</code>
       */
      public Builder setType(com.fx.productization.datanormalizer.domain.core.dto.ItemCodeTypeOuterClass.ItemCodeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.fx.productization.datanormalizer.domain.core.dto.ItemCodeType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object itemCode_ = "";
      /**
       * <code>optional string itemCode = 2;</code>
       */
      public java.lang.String getItemCode() {
        java.lang.Object ref = itemCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          itemCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string itemCode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getItemCodeBytes() {
        java.lang.Object ref = itemCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          itemCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string itemCode = 2;</code>
       */
      public Builder setItemCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        itemCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string itemCode = 2;</code>
       */
      public Builder clearItemCode() {
        
        itemCode_ = getDefaultInstance().getItemCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string itemCode = 2;</code>
       */
      public Builder setItemCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        itemCode_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCode)
    }

    // @@protoc_insertion_point(class_scope:com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCode)
    private static final com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode();
    }

    public static com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UnifyItemCode>
        PARSER = new com.google.protobuf.AbstractParser<UnifyItemCode>() {
      public UnifyItemCode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UnifyItemCode(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UnifyItemCode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UnifyItemCode> getParserForType() {
      return PARSER;
    }

    public com.fx.productization.datanormalizer.domain.core.dto.UnifyItemCodeOuterClass.UnifyItemCode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fx_productization_datanormalizer_domain_core_dto_UnifyItemCode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fx_productization_datanormalizer_domain_core_dto_UnifyItemCode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023UnifyItemCode.proto\0224com.fx.productiza" +
      "tion.datanormalizer.domain.core.dto\032\022Ite" +
      "mCodeType.proto\"s\n\rUnifyItemCode\022P\n\004type" +
      "\030\001 \001(\0162B.com.fx.productization.datanorma" +
      "lizer.domain.core.dto.ItemCodeType\022\020\n\010it" +
      "emCode\030\002 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fx.productization.datanormalizer.domain.core.dto.ItemCodeTypeOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_fx_productization_datanormalizer_domain_core_dto_UnifyItemCode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fx_productization_datanormalizer_domain_core_dto_UnifyItemCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fx_productization_datanormalizer_domain_core_dto_UnifyItemCode_descriptor,
        new java.lang.String[] { "Type", "ItemCode", });
    com.fx.productization.datanormalizer.domain.core.dto.ItemCodeTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
